### ISSUE TITLE
Some problems.

### ISSUE THREAD

**Issue by humanalways** [Abigale001/h2seqrec#2]
I tried to run your code on the server, but I ran into some problems as follows.
1. I can't find the file associated with 'time-list' and 'pre-training embedding'  as described in 2-b.
2. There is no  'train.py' in this repository as described in 2-c.
3. Files in your code need a tensorflow environment, not just a pytorch environment.

Could you please solve these problems?
Thanks a lot!

**Comment by Abigale001** [comment]
Hi, the readme has been updated. 
For problems 1 and 2, please download the code from OneDrive.
For problem 3, indeed, it also needs a TensorFlow environment.

**Comment by humanalways** [comment]
Thanks!
